var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  xx              o   #    xxx                                                  ",
   "  x           o   o  xxxx       xx                                 o          x ",
   "  x       o   o  xxxxxxxx!!!!!!!xx              o                  o          x ",
   "  x       o  xxxxxxxxxxxxxxxxxxxxx              o                  xx      o  x ",
   "  x  @ p xxxxxxxxxxxxxxxxxxxxxxxxx      yyy    yyy    yyy     p         k  o  x ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                     xxxxxxx    xxxxxxxxx ",
   "                                     x!!!!!!!!!!!!!!!!!!!!!x     x!!!!x         ",
   "                                     x!!!!!!!!!!!!!!!!!!!!!x     xxxxxx         ",
   "                                     x!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                                     xxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                 xxx           xxx         xxx      ",
   "                                               xx!!!xx       xx!!!xx     xx!!!xx    ",
   "                            o                  xx!!!xx       xx!!!xx     xx!!!xx    ",
   "                            o                    xvx           xvx         xvx      ",
   "  xx                  o   yyyyy                                                   x ",
   "  x                   o                                                           x ",
   "  x            o    yyyyy                                                         x ",
   "  x            o                          p                                       x ",
   "  x          yyyyy                        xxx                                     x ",
   "  x @                               #  xxxxxx     o             o           o     x ",
   "  xxxxxxxxxx                      xxxxxxxxxxx     o         p   o           o   k x ",
   "  xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxx   xxxxxxxxxx ",
   "           x!!!!!!!!!!!!!!!!!!!!!!x                    x!!!x         x!!!x          ",
   "           xxxxxxxxxxxxxxxxxxxxxxxx                    xxxxx         xxxxx          ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                                                    "],
  ["                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "  xx                                                                                ",
   "  x                                                                                 ",
   "  x                                                                                 ",
   "  x@                                                 o             o         o      ",
   "  xxx                                                o             o         o      ",
   "  xxxxxx o                               o     xx   xxx   xx      xxx       xxx   x ",
   "  xxxxxxxxx                              o     xx!!!xxx!!!xx    xx!!!xx   xx!!!xx x ",
   "  xxxxxxxxx    o   v   o          #    xxxxx   xxxxxxxxxxxxx    xx!!!xx   xx!!!xx x ",
   "  xxxx         o       o         xxxx                             xvx       xvx   x ",
   "  xxxx  o    yyyyy   yyyyy   p                                                    x ",
   "  xxxx  o                  xxxxxxxxxxx                         o        o         x ",
   "  xxxxxxxxxx               xxxxxxxxxxx                         o        o       k x ",
   "  xxxxxxxxxx!!!!!!!!!!!!!!!xxxxxxxxxxx                     xxxxxxxxxxxxxxxxxxxxxxxx ",
   "           x!!!!!!!!!!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!x                        ",
   "           xxxxxxxxxxxxxxxxx         x!!!!!!!!!!!!!!!!!!!!!x                        ",
   "                                     x!!!!!!!!!!!!!!!!!!!!!x                        ",
   "                                     xxxxxxxxxxxxxxxxxxxxxxx                        ",
   "                                                                                    ",
   "                                                                                    "],
  ["                                               xxx                                    ",
   "                                             xx!!!xx                                  ",
   "                                             xx!!!xx                                  ",
   "                                               xvx                                    ",
   "                                                                                      ",
   "  xx                                                                                  ",
   "  x                                                                                   ",
   "  x                                              o                      xxx            ",
   "  x@                                             o                    xx!!!xx         ",
   "  xxx                                       xxxxxxxxxxx               xx!!!xx         ",
   "  xxxxx                                     xxxxxxxxxxx         xxx     xvx           ",
   "  xxxxxxx                         o     xx  xxxxxxxxxxx           x                   ",
   "  xxxxxxx                         o     xx               p      o x                   ",
   "  xxxx o                          xxxxxxxx               xxxx   o x                   ",
   "  xxxx o                         xxxxxxxxx!!!!!!!!!!!!!!!x     xxxx                   ",
   "  xxxxxxxxxxx                       xxxxxx!!!!!!!!!!!!!!!x        x                   ",
   "  xxxxxxxxxxx o              xxx  o xxxxxxxxxxxxxxxxxxxxxxxxx     x                   ",
   "  xxxxxxxxxxx o     #             o x                    x        x                 x ",
   "           xxxx   yyyyy          xxxx                    x     xxxx                 x ",
   "           xxxx            xxxxxxxxxx                    x o                    o   x ",
   "           xxxx!!!!!!!!!!!!xxxxxxxxxx                    x o         p   xx     o k x ",
   "           xxxx!!!!!!!!!!!!xx                            xxxxxxxxxxxxxx      xxxxxxxx ",
   "           xxxxxxxxxxxxxxxxxx                                         x!!!!!!x        ",
   "                                                                      xxxxxxxx        "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "         x     x  xxxxx  x    x      x                 x  x  xx      x          ",
   "         x     x  x   x  x    x      x                 x  x  x x     x          ",
   "         x     x  x   x  x    x       x               x   x  x  x    x          ",
   "          x   x   x   x  x    x        x      x      x    x  x   x   x          ",
   "           x x    x   x  x    x         x    x x    x     x  x    x  x          ",
   "            x     x   x  x    x          x  x   x  x      x  x     x x          ",
   "            x     x   x  x    x           xx     xx       x  x      xx       xx ",
   "  xx        x     xxxxx  xxxxxx                                               x ",
   "  x                                                                           x ",
   "  x                                                                           x ",
   "  x                                                                           x ",
   "  x @                                                                         x ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;


/*["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x                  =                  x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "] */
